# Shared helper for post_analysis_*.jl modules: gives every PerformAnalysis() call its own
# fresh, timestamped output directory (mirroring the results/{timestamp}_{experiment_name}
# convention already used for simulation runs) instead of every module writing into the same
# fixed "results/analysis" path - so rerunning an analysis, or running a different one, never
# silently overwrites a previous run's charts/xlsx, even across a branch switch (results/ isn't
# git-tracked, so its contents persist across checkouts). Also writes a plain-text manifest
# alongside the output recording exactly which source result directories (and which git
# branch/commit) produced it, so a chart can always be traced back to its inputs without
# reading source code across branches.

module AnalysisOutput

using Dates

const RESULTS_ANALYSIS_ROOT = "results/analysis"

# Fresh output directory for one analysis run: results/analysis/{unix_timestamp}_{name}.
# Creates it (including RESULTS_ANALYSIS_ROOT itself if needed) and returns the path.
function NewOutputDir(name::AbstractString)
	dir = joinpath(RESULTS_ANALYSIS_ROOT, "$(round(Int, time()))_$(name)")
	mkpath(dir)
	return dir
end

function GitInfo()
	branch = try
		strip(read(`git rev-parse --abbrev-ref HEAD`, String))
	catch
		"unknown"
	end
	commit = try
		strip(read(`git rev-parse HEAD`, String))
	catch
		"unknown"
	end
	return branch, commit
end

# Writes sources.txt into output_dir: the git branch/commit that produced this run, optional
# free-form notes, and every (label => source result directory) pair that fed into it - sorted
# by label for a stable diff-friendly order. `sources` values are usually result directory
# paths (which themselves carry a Config/ subfolder from CopyConfigFiles!, so the full chain
# from chart -> source run -> exact experiment/market/agent YAML is traceable without needing
# anything beyond this file).
function WriteManifest(output_dir::AbstractString, sources::AbstractDict; notes::AbstractString="")
	branch, commit = GitInfo()
	open(joinpath(output_dir, "sources.txt"), "w") do io
		println(io, "generated: ", Dates.now())
		println(io, "git branch: ", branch)
		println(io, "git commit: ", commit)
		isempty(notes) || println(io, "notes: ", notes)
		println(io)
		println(io, "sources:")
		for key in sort(collect(keys(sources)))
			println(io, "  ", key, " => ", sources[key])
		end
	end
end

# Updates results/analysis/index.md with a pointer to the most recent run of one named
# analysis, so a casual lookup doesn't need to know an exact timestamp - keeps exactly one line
# per analysis name, rewriting the whole (small) file each time.
function UpdateLatestIndex(analysis_name::AbstractString, output_dir::AbstractString)
	index_path = joinpath(RESULTS_ANALYSIS_ROOT, "index.md")
	entries = Dict{String,String}()
	if isfile(index_path)
		for line in eachline(index_path)
			m = match(r"^- \*\*(.+?)\*\*: (.+)$", line)
			m === nothing && continue
			entries[m.captures[1]] = m.captures[2]
		end
	end
	entries[analysis_name] = "$output_dir  (as of $(Dates.now()))"

	open(index_path, "w") do io
		println(io, "# Latest run of each analysis")
		println(io)
		println(io, "Auto-generated by AnalysisOutput.UpdateLatestIndex - each entry is the most")
		println(io, "recent output directory for that analysis name; older runs stay on disk")
		println(io, "under their own timestamped directory rather than being deleted.")
		println(io)
		for name in sort(collect(keys(entries)))
			println(io, "- **$name**: $(entries[name])")
		end
	end
end

end;
