# Zero-price vs non-zero-price Gross Traded Volume comparison across solver/method permutations.
#
# Extends post_analysis_solver_comparison.jl's Gross Traded Volume (Clearing-MTU-capped 12:672,
# summed over every clearing's full look-ahead window) with a second dimension: for every
# delivery/target MTU touched by that gross volume, classify it by how many of the clearings that
# ever touched it recorded a price of (near) zero there - "always-zero" (every clearing agreed),
# "never-zero" (no clearing ever recorded zero there), or "sometimes-zero" (a mix - some clearings
# recorded zero, others didn't, typically because an earlier speculative clearing still expected
# renewable surplus that a later, firmer forecast resolved away). A given MTU keeps one
# classification, and every leg touching it (from every clearing) is bucketed the same way, so the
# three buckets partition the full Gross Traded Volume total exactly. always-zero/never-zero keep
# their original strict-unanimity definitions from the first version of this analysis; the
# sometimes-zero bucket is new, carved out of what used to be a single "non-zero-price" bucket -
# see the git history of this file for the empirical finding that motivated splitting it out:
# most of the residual cross-solver spread inside the old "non-zero" bucket turned out to be
# individual price=0 legs that just weren't unanimous at the MTU level.
#
# The point is to see whether the trading-volume differences between solver/method permutations
# (LP degeneracy - see post_analysis_solver_comparison.jl) concentrate in zero-price periods
# (where many dispatch vertices are equally optimal, so the solver's tie-breaking matters more).
# Wind and Solar are the only two agents that share a bid price (both bid €0/MWh - see
# validate_laura_agents.yaml; Base=€30, Shoulder=€80, Peak=€150), so whenever the clearing price
# is €0 they become mutually substitutable and solver tie-breaking has room to differ; at every
# other price level the marginal agent is uniquely identified by price, leaving no room for a tie.
#
# Storage (battery charge/discharge) gets its own separate chart/sheet, using throughput
# (|charge| + |discharge|) as its Gross Volume analog, read from the RAW per-clearing exports (it
# isn't a trading "Agent" in transactions.xlsx, so it has no equivalent there) - kept out of the
# generator totals/chart since it isn't "traded" in the same market-clearing sense. Storage shows
# the same signature as Wind/Solar: at a zero price, charging the battery with curtailed renewable
# surplus is exactly as "free" as curtailing it directly, so which one a solver picks is just as
# undetermined as the Wind/Solar split itself - empirically, storage throughput in the always-zero
# bucket varies ~3.6x across solver/method permutations (fixed36h) while the never-zero bucket
# varies by only ~4%.

module PostAnalysisPriceBucketComparison

using XLSX, DataFrames, Plots, StatsPlots, Statistics

include("./analysis_output.jl")
using .AnalysisOutput

# result directories for each solver/method permutation - same runs as
# post_analysis_solver_comparison.jl (kept in sync by hand; see solver_permutation_dirs.jl,
# generated by run_solver_permutations.jl in the scratchpad, for the source of these paths).
# Fixed is pinned to demand_adjust=false, ex_post_transactions=false, same as Rolling's own
# default, so the two cases are on equal footing - see post_analysis_solver_comparison.jl for
# why the original demand_adjust=true Fixed dirs shifted the 3 Gurobi columns by a real,
# solver-dependent amount via LP-degeneracy sensitivity.
fixed_result_dirs = Dict{String,String}(
	"HiGHS + simplex" => "results/1789119039_fixed_highs_simplex_both_false",
	"HiGHS + IPM" => "results/1789119090_fixed_highs_ipm_both_false",
	"Gurobi + simplex" => "results/1789116424_toggle_fixed_gurobi_simplex_da_false_ept_false",
	"Gurobi + dual_simplex" => "results/1789116515_toggle_fixed_gurobi_dualsimplex_da_false_ept_false",
	"Gurobi + IPM" => "results/1789116611_toggle_fixed_gurobi_ipm_da_false_ept_false",
)

rolling_result_dirs = Dict{String,String}(
	"HiGHS + simplex" => "results/1789038789_solvercmp_rolling_highs_simplex",
	"HiGHS + IPM" => "results/1789038858_solvercmp_rolling_highs_ipm",
	"Gurobi + simplex" => "results/1789038907_solvercmp_rolling_gurobi_simplex",
	"Gurobi + dual_simplex" => "results/1789038954_solvercmp_rolling_gurobi_dualsimplex",
	"Gurobi + IPM" => "results/1789038992_solvercmp_rolling_gurobi_ipm",
)

laura_data_dir = "../DATA/_laura_data_w_adj"
laura_file_prefix = Dict{String,String}(
	"Fixed" => "decisionvariables_Fixed36h_",
	"Rolling" => "decisionvariables_Rolling36h_",
)

# per-clearing RAW export prefix for our own runs, used to compute Storage's Gross Throughput
# the same way Gross Traded Volume is computed for generators (summed across every clearing's
# full look-ahead window, not just the executed leg) - storage isn't a trading "Agent" in
# transactions.xlsx, so it has no equivalent there and has to be read from the RAW per-clearing
# exports instead, same as Laura's reference data already is. The prefix comes from the
# experiment config's own `name:` field (validate_laura_fixed_36 / validate_laura_rolling_36),
# not from the result directory's name, since every solver/method permutation shares the same
# underlying experiment config and therefore the same RAW filename prefix.
raw_dispatch_prefix = Dict{String,String}(
	"Fixed" => "decisionvariables_validate_laura_fixed_36_",
	"Rolling" => "decisionvariables_validate_laura_rolling_36_",
)

generators = ["Base", "Shoulder", "Peak", "Wind", "Solar"]
generator_agent_names = Dict{String,String}(
	"Base" => "3G_Base", "Shoulder" => "4G_Shoulder", "Peak" => "5G_Peak",
	"Wind" => "6G_Wind", "Solar" => "7G_Solar",
)

# Storage is included alongside the five generators in the by-series breakdown, using
# StorageCharge + StorageDischarge ("throughput") as its Gross Volume analog - see
# PriceBucketVolumesForRun/PriceBucketVolumesForLaura for how it's computed
all_series = vcat(generators, ["Storage"])

time_range = 12:672
atol = 1e-6

category_order = ["Reference (HiGHS + default)", "HiGHS + simplex", "HiGHS + IPM", "Gurobi + simplex", "Gurobi + dual_simplex", "Gurobi + IPM"]

quantity_symbol = Symbol("Quantity (MWh)")
price_symbol = Symbol("Price (€/MWh)")
mtu_symbol = Symbol("Market Time Unit")
clearing_mtu_symbol = Symbol("Clearing MTU")

# three-way classification of every target MTU by how many of the clearings touching it recorded
# a price of (near) zero there: always-zero (every price ~0), never-zero (no price ~0), or
# sometimes-zero (a mix of both - the MTU's own price disagreement across clearings, not touched
# by the strict-unanimity always/never split at all)
function ClassifyMTUsByPrice(target_mtus, prices)
	price_lists = Dict{Int,Vector{Float64}}()
	for (m, p) in zip(target_mtus, prices)
		push!(get!(price_lists, Int(round(m)), Float64[]), Float64(p))
	end
	always_zero_mtus = Set{Int}()
	sometimes_zero_mtus = Set{Int}()
	never_zero_mtus = Set{Int}()
	for (m, ps) in price_lists
		any_zero = any(abs.(ps) .< atol)
		all_zero = all(abs.(ps) .< atol)
		if all_zero
			push!(always_zero_mtus, m)
		elseif any_zero
			push!(sometimes_zero_mtus, m)
		else
			push!(never_zero_mtus, m)
		end
	end
	return always_zero_mtus, sometimes_zero_mtus, never_zero_mtus
end

# Gross Traded Volume, split by price bucket, for one of our own runs - same Clearing-MTU-capped
# transactions.xlsx source as GrossTradedVolumeForRun in post_analysis_solver_comparison.jl.
BucketVolumes = NamedTuple{(:always_zero, :sometimes_zero, :never_zero),Tuple{Float64,Float64,Float64}}

function PriceBucketVolumesForRun(result_dir, case)
	tx = DataFrame(XLSX.readtable(joinpath(result_dir, "transactions.xlsx"), "data"))
	tx_capped = tx[(time_range.start .<= tx[!, clearing_mtu_symbol] .<= time_range.stop), :]

	always_zero_mtus, sometimes_zero_mtus, never_zero_mtus = ClassifyMTUsByPrice(tx_capped[!, mtu_symbol], tx_capped[!, price_symbol])

	volumes = Dict{String,BucketVolumes}()
	for gen in generators
		rows = tx_capped[tx_capped.Agent .== generator_agent_names[gen], :]
		az_vol = sum(abs.(rows[in.(rows[!, mtu_symbol], Ref(always_zero_mtus)), quantity_symbol]); init=0.0)
		sz_vol = sum(abs.(rows[in.(rows[!, mtu_symbol], Ref(sometimes_zero_mtus)), quantity_symbol]); init=0.0)
		nz_vol = sum(abs.(rows[in.(rows[!, mtu_symbol], Ref(never_zero_mtus)), quantity_symbol]); init=0.0)
		volumes[gen] = (always_zero=az_vol, sometimes_zero=sz_vol, never_zero=nz_vol)
	end

	# Storage's Gross Throughput, bucketed using the SAME always/sometimes/never-zero MTU sets
	# computed above from the generators' own transactions - price is a single per-clearing
	# settlement value shared by every agent (and storage) transacting in that clearing, so
	# storage's own per-leg prices would classify every MTU identically; reusing the sets here
	# avoids recomputing them from the RAW files' own price column
	prefix = raw_dispatch_prefix[case]
	az_storage = 0.0
	sz_storage = 0.0
	nz_storage = 0.0
	for mtu_cleared in time_range
		path = joinpath(result_dir, "RAW", "$(prefix)$(mtu_cleared).xlsx")
		isfile(path) || continue
		df = DataFrame(XLSX.readtable(path, "data"))
		for row in eachrow(df)
			m = Int(row.mtu)
			throughput = abs(row.StorageCharge) + abs(row.StorageDischarge)
			if m in always_zero_mtus
				az_storage += throughput
			elseif m in sometimes_zero_mtus
				sz_storage += throughput
			elseif m in never_zero_mtus
				nz_storage += throughput
			end
		end
	end
	volumes["Storage"] = (always_zero=az_storage, sometimes_zero=sz_storage, never_zero=nz_storage)

	return volumes, length(always_zero_mtus), length(sometimes_zero_mtus), length(never_zero_mtus)
end

# Gross Traded Volume, split by price bucket, for Laura's raw per-clearing reference data - same
# source files as GrossTradedVolumeForLaura, which each carry one row per target mtu in that
# clearing's window with its own "price" and "<gen>_adj" columns.
function PriceBucketVolumesForLaura(case)
	prefix = laura_file_prefix[case]

	price_lists = Dict{Int,Vector{Float64}}()
	volume_by_mtu = Dict{String,Dict{Int,Float64}}(gen => Dict{Int,Float64}() for gen in generators)
	volume_by_mtu["Storage"] = Dict{Int,Float64}()

	for mtu_cleared in time_range
		path = joinpath(laura_data_dir, "$(prefix)$(mtu_cleared).xlsx")
		isfile(path) || continue
		df = DataFrame(XLSX.readtable(path, "data"))
		for row in eachrow(df)
			m = Int(row.mtu)
			push!(get!(price_lists, m, Float64[]), Float64(row.price))
			for gen in generators
				d = volume_by_mtu[gen]
				d[m] = get(d, m, 0.0) + abs(row[Symbol("$(gen)_adj")])
			end
			ds = volume_by_mtu["Storage"]
			ds[m] = get(ds, m, 0.0) + abs(row.StorageCharge) + abs(row.StorageDischarge)
		end
	end

	always_zero_mtus = Set{Int}()
	sometimes_zero_mtus = Set{Int}()
	never_zero_mtus = Set{Int}()
	for (m, ps) in price_lists
		any_zero = any(abs.(ps) .< atol)
		all_zero = all(abs.(ps) .< atol)
		if all_zero
			push!(always_zero_mtus, m)
		elseif any_zero
			push!(sometimes_zero_mtus, m)
		else
			push!(never_zero_mtus, m)
		end
	end

	volumes = Dict{String,BucketVolumes}()
	for gen in all_series
		d = volume_by_mtu[gen]
		az_vol = sum((v for (m, v) in d if m in always_zero_mtus); init=0.0)
		sz_vol = sum((v for (m, v) in d if m in sometimes_zero_mtus); init=0.0)
		nz_vol = sum((v for (m, v) in d if m in never_zero_mtus); init=0.0)
		volumes[gen] = (always_zero=az_vol, sometimes_zero=sz_vol, never_zero=nz_vol)
	end
	return volumes, length(always_zero_mtus), length(sometimes_zero_mtus), length(never_zero_mtus)
end

# Loads per-series (5 generators + Storage) Gross Volume by price bucket for every category
# (Laura + each solver/method permutation) for one case - this is the expensive part (reads every
# run's transactions.xlsx plus, for Storage, all 661 RAW per-clearing exports), done once per case
# and then sliced into separate generator-only / Storage-only DataFrames by BuildBucketDataFrame,
# so the two downstream charts don't each pay for their own copy of this I/O.
function LoadAllVolumes(case, result_dirs)
	println("computing price-bucket gross volume for case: $case")

	all_volumes = Dict{String,Any}()
	mtu_counts = Dict{String,Tuple{Int,Int,Int}}()

	println("  loading: Laura (reference)")
	v, naz, nsz, nnz = PriceBucketVolumesForLaura(case)
	all_volumes["Reference (HiGHS + default)"] = v
	mtu_counts["Reference (HiGHS + default)"] = (naz, nsz, nnz)

	for (config_label, dir) in result_dirs
		println("  loading: $config_label ($dir)")
		v, naz, nsz, nnz = PriceBucketVolumesForRun(dir, case)
		all_volumes[config_label] = v
		mtu_counts[config_label] = (naz, nsz, nnz)
	end

	return all_volumes, mtu_counts
end

# Builds a DataFrame with one row per (category, series) - for `series_list = generators` this is
# the generator-only Gross Traded Volume breakdown; for `series_list = ["Storage"]` it's Storage's
# Gross Volume (throughput = |charge| + |discharge|, Gross Traded Volume has no direct analog for
# a bidirectional asset) on its own, kept out of the generator totals since it isn't "traded" in
# the same market-clearing sense.
function BuildBucketDataFrame(case, all_volumes, mtu_counts, series_list)
	df = DataFrame(Case=String[], Configuration=String[], Generator=String[],
		AlwaysZeroVolume=Float64[], SometimesZeroVolume=Float64[], NeverZeroVolume=Float64[], TotalVolume=Float64[],
		AlwaysZeroMTUCount=Int[], SometimesZeroMTUCount=Int[], NeverZeroMTUCount=Int[])

	for cat in category_order
		haskey(all_volumes, cat) || continue
		volumes = all_volumes[cat]
		naz, nsz, nnz = mtu_counts[cat]
		for gen in series_list
			azv, szv, nzv = volumes[gen]
			push!(df, (case, cat, gen, azv, szv, nzv, azv + szv + nzv, naz, nsz, nnz))
		end
	end

	return df
end

# One row per (Case, Configuration): totals across generators AND storage, plus each
# configuration's always-zero share of its own grand total - the figure that directly answers
# "do the solver/method differences concentrate in zero-price periods?"
function PriceBucketSummary(df)
	summary = combine(groupby(df, [:Case, :Configuration]),
		:AlwaysZeroVolume => sum => :AlwaysZeroVolume,
		:SometimesZeroVolume => sum => :SometimesZeroVolume,
		:NeverZeroVolume => sum => :NeverZeroVolume,
		:TotalVolume => sum => :TotalVolume,
		:AlwaysZeroMTUCount => first => :AlwaysZeroMTUCount,
		:SometimesZeroMTUCount => first => :SometimesZeroMTUCount,
		:NeverZeroMTUCount => first => :NeverZeroMTUCount,
	)
	summary[!, :AlwaysZeroShare] = summary.AlwaysZeroVolume ./ summary.TotalVolume
	return summary
end

# For each case, the spread (max-min) across our own 5 solver/method permutations (excluding
# the Laura reference, which isn't one of the permutations being compared) within each price
# bucket - and that spread as a fraction of the bucket's own mean volume, so the two buckets are
# comparable even though zero-price and non-zero-price hours don't split the horizon evenly.
function PermutationSpreadByBucket(summary)
	ours = summary[summary.Configuration .!= "Reference (HiGHS + default)", :]
	spread = combine(groupby(ours, :Case),
		:AlwaysZeroVolume => (v -> maximum(v) - minimum(v)) => :AlwaysZeroVolumeSpread,
		:AlwaysZeroVolume => (v -> Statistics.mean(v)) => :AlwaysZeroVolumeMean,
		:SometimesZeroVolume => (v -> maximum(v) - minimum(v)) => :SometimesZeroVolumeSpread,
		:SometimesZeroVolume => (v -> Statistics.mean(v)) => :SometimesZeroVolumeMean,
		:NeverZeroVolume => (v -> maximum(v) - minimum(v)) => :NeverZeroVolumeSpread,
		:NeverZeroVolume => (v -> Statistics.mean(v)) => :NeverZeroVolumeMean,
	)
	spread[!, :AlwaysZeroSpreadPct] = spread.AlwaysZeroVolumeSpread ./ spread.AlwaysZeroVolumeMean
	spread[!, :SometimesZeroSpreadPct] = spread.SometimesZeroVolumeSpread ./ spread.SometimesZeroVolumeMean
	spread[!, :NeverZeroSpreadPct] = spread.NeverZeroVolumeSpread ./ spread.NeverZeroVolumeMean
	return spread
end

function PlotPriceBucketComparison(title, ylabel, summary_case)
	# groupedbar's :stack draws the first column on top, so feed [AlwaysZero, SometimesZero,
	# NeverZero] to anchor Never-zero-price volume at the bottom of every bar (baseline 0) -
	# since that segment's own height barely changes across configurations, anchoring it at a
	# fixed baseline makes its stability plainly visible, rather than having it float on top of
	# the growing always-zero/sometimes-zero segments above it
	data = zeros(nrow(summary_case), 3) # MWh -> million MWh
	for (i, row) in enumerate(eachrow(summary_case))
		data[i, 1] = row.AlwaysZeroVolume / 1e6
		data[i, 2] = row.SometimesZeroVolume / 1e6
		data[i, 3] = row.NeverZeroVolume / 1e6
	end

	p = groupedbar(
		data,
		bar_position = :stack,
		label = ["Always-zero-price MTUs" "Sometimes-zero-price MTUs" "Never-zero-price MTUs"],
		color = [RGB(0.85, 0.55, 0.13) RGB(0.55, 0.35, 0.65) RGB(0.16, 0.47, 0.84)],
		xticks = (1:nrow(summary_case), summary_case.Configuration),
		xrotation = 20,
		ylabel = ylabel,
		title = title,
		titlefontsize = 11,
		legend = :outertopright,
		size = (950, 550),
		left_margin = 14Plots.mm,
		bottom_margin = 20Plots.mm,
	)

	return p
end

# Same three price buckets as PlotPriceBucketComparison, but normalized by each bucket's own MTU
# count (average Gross Traded Volume per bucketed MTU, summed across every clearing that touched
# it) and drawn as side-by-side (dodged) bars instead of stacked - stacking hides bucket-to-bucket
# intensity differences behind each other's height, since always-zero/sometimes-zero/never-zero
# buckets don't contain the same number of MTUs to begin with (e.g. Fixed: ~170 always-zero vs.
# ~422 never-zero) so raw totals aren't a fair per-MTU comparison across buckets or permutations.
function PlotPriceBucketAveragePerMTU(title, ylabel, summary_case)
	data = zeros(nrow(summary_case), 3)
	for (i, row) in enumerate(eachrow(summary_case))
		data[i, 1] = row.AlwaysZeroMTUCount > 0 ? row.AlwaysZeroVolume / row.AlwaysZeroMTUCount : 0.0
		data[i, 2] = row.SometimesZeroMTUCount > 0 ? row.SometimesZeroVolume / row.SometimesZeroMTUCount : 0.0
		data[i, 3] = row.NeverZeroMTUCount > 0 ? row.NeverZeroVolume / row.NeverZeroMTUCount : 0.0
	end

	p = groupedbar(
		data,
		bar_position = :dodge,
		label = ["Always-zero-price MTUs" "Sometimes-zero-price MTUs" "Never-zero-price MTUs"],
		color = [RGB(0.85, 0.55, 0.13) RGB(0.55, 0.35, 0.65) RGB(0.16, 0.47, 0.84)],
		xticks = (1:nrow(summary_case), summary_case.Configuration),
		xrotation = 20,
		ylabel = ylabel,
		title = title,
		titlefontsize = 11,
		legend = :outertopright,
		size = (950, 550),
		left_margin = 14Plots.mm,
		bottom_margin = 20Plots.mm,
	)

	return p
end

function PerformAnalysis()
	output_dir = AnalysisOutput.NewOutputDir("price_bucket_comparison")

	fixed_volumes, fixed_counts = LoadAllVolumes("Fixed", fixed_result_dirs)
	rolling_volumes, rolling_counts = LoadAllVolumes("Rolling", rolling_result_dirs)

	# --- generators only (the headline chart) ---
	gen_fixed_df = BuildBucketDataFrame("Fixed", fixed_volumes, fixed_counts, generators)
	gen_rolling_df = BuildBucketDataFrame("Rolling", rolling_volumes, rolling_counts, generators)
	gen_combined_df = vcat(gen_fixed_df, gen_rolling_df)

	gen_summary = PriceBucketSummary(gen_combined_df)
	println(gen_summary)
	gen_spread = PermutationSpreadByBucket(gen_summary)
	println(gen_spread)

	p_fixed = PlotPriceBucketComparison(
		"Fixed 36h - Gross Traded Volume by price bucket, per solver / method",
		"Gross Traded Volume (million MWh)",
		gen_summary[gen_summary.Case .== "Fixed", :],
	)
	savefig(p_fixed, "$output_dir/trading_volume_price_bucket_fixed36h.png")
	println("saved: $output_dir/trading_volume_price_bucket_fixed36h.png")

	p_rolling = PlotPriceBucketComparison(
		"Rolling 36h - Gross Traded Volume by price bucket, per solver / method",
		"Gross Traded Volume (million MWh)",
		gen_summary[gen_summary.Case .== "Rolling", :],
	)
	savefig(p_rolling, "$output_dir/trading_volume_price_bucket_rolling36h.png")
	println("saved: $output_dir/trading_volume_price_bucket_rolling36h.png")

	# --- same generator data, but average-per-bucketed-MTU and side-by-side instead of stacked ---
	p_fixed_avg = PlotPriceBucketAveragePerMTU(
		"Fixed 36h - avg Gross Traded Volume per MTU by price bucket, per solver / method",
		"Avg Gross Traded Volume per MTU (MWh)",
		gen_summary[gen_summary.Case .== "Fixed", :],
	)
	savefig(p_fixed_avg, "$output_dir/trading_volume_price_bucket_avg_per_mtu_fixed36h.png")
	println("saved: $output_dir/trading_volume_price_bucket_avg_per_mtu_fixed36h.png")

	p_rolling_avg = PlotPriceBucketAveragePerMTU(
		"Rolling 36h - avg Gross Traded Volume per MTU by price bucket, per solver / method",
		"Avg Gross Traded Volume per MTU (MWh)",
		gen_summary[gen_summary.Case .== "Rolling", :],
	)
	savefig(p_rolling_avg, "$output_dir/trading_volume_price_bucket_avg_per_mtu_rolling36h.png")
	println("saved: $output_dir/trading_volume_price_bucket_avg_per_mtu_rolling36h.png")

	# --- storage only (separate chart, not folded into the generator totals) ---
	storage_fixed_df = BuildBucketDataFrame("Fixed", fixed_volumes, fixed_counts, ["Storage"])
	storage_rolling_df = BuildBucketDataFrame("Rolling", rolling_volumes, rolling_counts, ["Storage"])
	storage_combined_df = vcat(storage_fixed_df, storage_rolling_df)

	storage_summary = PriceBucketSummary(storage_combined_df)
	println(storage_summary)
	storage_spread = PermutationSpreadByBucket(storage_summary)
	println(storage_spread)

	p_storage_fixed = PlotPriceBucketComparison(
		"Fixed 36h - Storage Gross Throughput by price bucket, per solver / method",
		"Storage Gross Throughput (million MWh)",
		storage_summary[storage_summary.Case .== "Fixed", :],
	)
	savefig(p_storage_fixed, "$output_dir/storage_throughput_price_bucket_fixed36h.png")
	println("saved: $output_dir/storage_throughput_price_bucket_fixed36h.png")

	p_storage_rolling = PlotPriceBucketComparison(
		"Rolling 36h - Storage Gross Throughput by price bucket, per solver / method",
		"Storage Gross Throughput (million MWh)",
		storage_summary[storage_summary.Case .== "Rolling", :],
	)
	savefig(p_storage_rolling, "$output_dir/storage_throughput_price_bucket_rolling36h.png")
	println("saved: $output_dir/storage_throughput_price_bucket_rolling36h.png")

	XLSX.writetable("$output_dir/price_bucket_trading_volume_details.xlsx",
		"by_generator" => gen_combined_df,
		"summary" => gen_summary,
		"permutation_spread" => gen_spread,
		"storage" => storage_combined_df,
		"storage_summary" => storage_summary,
		"storage_spread" => storage_spread;
		overwrite=true,
	)
	println("saved: $output_dir/price_bucket_trading_volume_details.xlsx")

	sources = merge(
		Dict("Fixed: $k" => v for (k, v) in fixed_result_dirs),
		Dict("Rolling: $k" => v for (k, v) in rolling_result_dirs),
		Dict("Reference (Laura) data dir" => laura_data_dir),
	)
	AnalysisOutput.WriteManifest(output_dir, sources)
	AnalysisOutput.UpdateLatestIndex("price_bucket_comparison", output_dir)

	return (p_fixed, p_rolling, p_fixed_avg, p_rolling_avg, p_storage_fixed, p_storage_rolling, gen_combined_df, gen_summary, gen_spread, storage_combined_df, storage_summary, storage_spread)
end

end;
