# Zero-price vs non-zero-price Gross Traded Volume comparison across solver/method permutations.
#
# Extends post_analysis_solver_comparison.jl's Gross Traded Volume (Clearing-MTU-capped 12:672,
# summed over every clearing's full look-ahead window) with a second dimension: for every
# delivery/target MTU touched by that gross volume, classify it as "zero-price" only if EVERY
# clearing that ever touched it recorded a price of (near) zero there - any disagreement between
# clearings puts the MTU in the "non-zero-price" bucket. This is a strict-unanimity definition
# (agreed with the user), not "the executed price is zero" and not "this one leg's own price is
# zero" - a given MTU keeps one classification, and every leg touching it (from every clearing)
# is bucketed the same way, so the split partitions the full Gross Traded Volume total exactly.
#
# The point is to see whether the trading-volume differences between solver/method permutations
# (LP degeneracy - see post_analysis_solver_comparison.jl) concentrate in zero-price periods
# (where many dispatch vertices are equally optimal, so the solver's tie-breaking matters more)
# or are spread evenly across zero- and non-zero-price hours.

module PostAnalysisPriceBucketComparison

using XLSX, DataFrames, Plots, StatsPlots, Statistics

results_path_base = "results/analysis"

# result directories for each solver/method permutation - same runs as
# post_analysis_solver_comparison.jl (kept in sync by hand; see solver_permutation_dirs.jl,
# generated by run_solver_permutations.jl in the scratchpad, for the source of these paths)
fixed_result_dirs = Dict{String,String}(
	"HiGHS + simplex" => "results/1789039031_solvercmp_fixed_highs_simplex",
	"HiGHS + IPM" => "results/1789039064_solvercmp_fixed_highs_ipm",
	"Gurobi + simplex" => "results/1789039101_solvercmp_fixed_gurobi_simplex",
	"Gurobi + dual_simplex" => "results/1789039129_solvercmp_fixed_gurobi_dualsimplex",
	"Gurobi + IPM" => "results/1789039159_solvercmp_fixed_gurobi_ipm",
)

rolling_result_dirs = Dict{String,String}(
	"HiGHS + simplex" => "results/1789038789_solvercmp_rolling_highs_simplex",
	"HiGHS + IPM" => "results/1789038858_solvercmp_rolling_highs_ipm",
	"Gurobi + simplex" => "results/1789038907_solvercmp_rolling_gurobi_simplex",
	"Gurobi + dual_simplex" => "results/1789038954_solvercmp_rolling_gurobi_dualsimplex",
	"Gurobi + IPM" => "results/1789038992_solvercmp_rolling_gurobi_ipm",
)

laura_data_dir = "../DATA/_laura_data_w_adj"
laura_file_prefix = Dict{String,String}(
	"Fixed" => "decisionvariables_Fixed36h_",
	"Rolling" => "decisionvariables_Rolling36h_",
)

generators = ["Base", "Shoulder", "Peak", "Wind", "Solar"]
generator_agent_names = Dict{String,String}(
	"Base" => "3G_Base", "Shoulder" => "4G_Shoulder", "Peak" => "5G_Peak",
	"Wind" => "6G_Wind", "Solar" => "7G_Solar",
)

time_range = 12:672
atol = 1e-6

category_order = ["Reference (HiGHS + default)", "HiGHS + simplex", "HiGHS + IPM", "Gurobi + simplex", "Gurobi + dual_simplex", "Gurobi + IPM"]

quantity_symbol = Symbol("Quantity (MWh)")
price_symbol = Symbol("Price (€/MWh)")
mtu_symbol = Symbol("Market Time Unit")
clearing_mtu_symbol = Symbol("Clearing MTU")

function CleanDirectory(path)
	mkpath(path)
end

# strict-unanimity classification: a target MTU is "zero-price" only if every price recorded
# for it (across every clearing that ever touched it) is within atol of zero
function ClassifyMTUsByPrice(target_mtus, prices)
	price_lists = Dict{Int,Vector{Float64}}()
	for (m, p) in zip(target_mtus, prices)
		push!(get!(price_lists, Int(round(m)), Float64[]), Float64(p))
	end
	zero_mtus = Set{Int}(m for (m, ps) in price_lists if all(abs.(ps) .< atol))
	nonzero_mtus = Set{Int}(m for (m, ps) in price_lists if !all(abs.(ps) .< atol))
	return zero_mtus, nonzero_mtus
end

# Gross Traded Volume, split by price bucket, for one of our own runs - same Clearing-MTU-capped
# transactions.xlsx source as GrossTradedVolumeForRun in post_analysis_solver_comparison.jl.
function PriceBucketVolumesForRun(result_dir)
	tx = DataFrame(XLSX.readtable(joinpath(result_dir, "transactions.xlsx"), "data"))
	tx_capped = tx[(time_range.start .<= tx[!, clearing_mtu_symbol] .<= time_range.stop), :]

	zero_mtus, nonzero_mtus = ClassifyMTUsByPrice(tx_capped[!, mtu_symbol], tx_capped[!, price_symbol])

	volumes = Dict{String,NamedTuple{(:zero, :nonzero),Tuple{Float64,Float64}}}()
	for gen in generators
		rows = tx_capped[tx_capped.Agent .== generator_agent_names[gen], :]
		zero_vol = sum(abs.(rows[in.(rows[!, mtu_symbol], Ref(zero_mtus)), quantity_symbol]); init=0.0)
		nonzero_vol = sum(abs.(rows[in.(rows[!, mtu_symbol], Ref(nonzero_mtus)), quantity_symbol]); init=0.0)
		volumes[gen] = (zero=zero_vol, nonzero=nonzero_vol)
	end
	return volumes, length(zero_mtus), length(nonzero_mtus)
end

# Gross Traded Volume, split by price bucket, for Laura's raw per-clearing reference data - same
# source files as GrossTradedVolumeForLaura, which each carry one row per target mtu in that
# clearing's window with its own "price" and "<gen>_adj" columns.
function PriceBucketVolumesForLaura(case)
	prefix = laura_file_prefix[case]

	price_lists = Dict{Int,Vector{Float64}}()
	volume_by_mtu = Dict{String,Dict{Int,Float64}}(gen => Dict{Int,Float64}() for gen in generators)

	for mtu_cleared in time_range
		path = joinpath(laura_data_dir, "$(prefix)$(mtu_cleared).xlsx")
		isfile(path) || continue
		df = DataFrame(XLSX.readtable(path, "data"))
		for row in eachrow(df)
			m = Int(row.mtu)
			push!(get!(price_lists, m, Float64[]), Float64(row.price))
			for gen in generators
				d = volume_by_mtu[gen]
				d[m] = get(d, m, 0.0) + abs(row[Symbol("$(gen)_adj")])
			end
		end
	end

	zero_mtus = Set{Int}(m for (m, ps) in price_lists if all(abs.(ps) .< atol))
	nonzero_mtus = Set{Int}(m for (m, ps) in price_lists if !all(abs.(ps) .< atol))

	volumes = Dict{String,NamedTuple{(:zero, :nonzero),Tuple{Float64,Float64}}}()
	for gen in generators
		d = volume_by_mtu[gen]
		zero_vol = sum((v for (m, v) in d if m in zero_mtus); init=0.0)
		nonzero_vol = sum((v for (m, v) in d if m in nonzero_mtus); init=0.0)
		volumes[gen] = (zero=zero_vol, nonzero=nonzero_vol)
	end
	return volumes, length(zero_mtus), length(nonzero_mtus)
end

# Gathers per-generator zero/non-zero Gross Traded Volume for every category (Laura + each
# solver/method permutation) for one case, as a DataFrame with one row per (category, generator)
# - this is both the plot's source data and what gets exported to xlsx.
function PriceBucketDataFrame(case, result_dirs)
	println("computing price-bucket gross traded volume for case: $case")

	all_volumes = Dict{String,Any}()
	mtu_counts = Dict{String,Tuple{Int,Int}}()

	println("  loading: Laura (reference)")
	v, nz, nnz = PriceBucketVolumesForLaura(case)
	all_volumes["Reference (HiGHS + default)"] = v
	mtu_counts["Reference (HiGHS + default)"] = (nz, nnz)

	for (config_label, dir) in result_dirs
		println("  loading: $config_label ($dir)")
		v, nz, nnz = PriceBucketVolumesForRun(dir)
		all_volumes[config_label] = v
		mtu_counts[config_label] = (nz, nnz)
	end

	df = DataFrame(Case=String[], Configuration=String[], Generator=String[],
		ZeroPriceVolume=Float64[], NonZeroPriceVolume=Float64[], TotalVolume=Float64[],
		ZeroPriceMTUCount=Int[], NonZeroPriceMTUCount=Int[])

	for cat in category_order
		haskey(all_volumes, cat) || continue
		volumes = all_volumes[cat]
		nz, nnz = mtu_counts[cat]
		for gen in generators
			zv, nzv = volumes[gen]
			push!(df, (case, cat, gen, zv, nzv, zv + nzv, nz, nnz))
		end
	end

	return df
end

# One row per (Case, Configuration): totals across generators, plus each configuration's zero-
# price share of its own total Gross Traded Volume - the figure that directly answers "do the
# solver/method differences concentrate in zero-price periods?"
function PriceBucketSummary(df)
	summary = combine(groupby(df, [:Case, :Configuration]),
		:ZeroPriceVolume => sum => :ZeroPriceVolume,
		:NonZeroPriceVolume => sum => :NonZeroPriceVolume,
		:TotalVolume => sum => :TotalVolume,
		:ZeroPriceMTUCount => first => :ZeroPriceMTUCount,
		:NonZeroPriceMTUCount => first => :NonZeroPriceMTUCount,
	)
	summary[!, :ZeroPriceShare] = summary.ZeroPriceVolume ./ summary.TotalVolume
	return summary
end

# For each case, the spread (max-min) across our own 5 solver/method permutations (excluding
# the Laura reference, which isn't one of the permutations being compared) within each price
# bucket - and that spread as a fraction of the bucket's own mean volume, so the two buckets are
# comparable even though zero-price and non-zero-price hours don't split the horizon evenly.
function PermutationSpreadByBucket(summary)
	ours = summary[summary.Configuration .!= "Reference (HiGHS + default)", :]
	spread = combine(groupby(ours, :Case),
		:ZeroPriceVolume => (v -> maximum(v) - minimum(v)) => :ZeroPriceVolumeSpread,
		:ZeroPriceVolume => (v -> Statistics.mean(v)) => :ZeroPriceVolumeMean,
		:NonZeroPriceVolume => (v -> maximum(v) - minimum(v)) => :NonZeroPriceVolumeSpread,
		:NonZeroPriceVolume => (v -> Statistics.mean(v)) => :NonZeroPriceVolumeMean,
	)
	spread[!, :ZeroPriceSpreadPct] = spread.ZeroPriceVolumeSpread ./ spread.ZeroPriceVolumeMean
	spread[!, :NonZeroPriceSpreadPct] = spread.NonZeroPriceVolumeSpread ./ spread.NonZeroPriceVolumeMean
	return spread
end

function PlotPriceBucketComparison(case, summary_case)
	# groupedbar's :stack draws the first column on top, so feed [Zero, NonZero] to anchor
	# Non-zero-price volume at the bottom of every bar (baseline 0) - since that segment's own
	# height barely changes across configurations, anchoring it at a fixed baseline makes its
	# stability plainly visible, rather than having it float on top of the growing zero-price base
	data = zeros(nrow(summary_case), 2) # MWh -> million MWh
	for (i, row) in enumerate(eachrow(summary_case))
		data[i, 1] = row.ZeroPriceVolume / 1e6
		data[i, 2] = row.NonZeroPriceVolume / 1e6
	end

	p = groupedbar(
		data,
		bar_position = :stack,
		label = ["Zero-price MTUs" "Non-zero-price MTUs"],
		color = [RGB(0.85, 0.55, 0.13) RGB(0.16, 0.47, 0.84)],
		xticks = (1:nrow(summary_case), summary_case.Configuration),
		xrotation = 20,
		ylabel = "Gross Traded Volume (million MWh)",
		title = "$case 36h - Gross Traded Volume by price bucket, per solver / method",
		legend = :outertopright,
		size = (900, 550),
		left_margin = 10Plots.mm,
		bottom_margin = 20Plots.mm,
	)

	return p
end

function PerformAnalysis()
	CleanDirectory(results_path_base)

	fixed_df = PriceBucketDataFrame("Fixed", fixed_result_dirs)
	rolling_df = PriceBucketDataFrame("Rolling", rolling_result_dirs)
	combined_df = vcat(fixed_df, rolling_df)

	summary = PriceBucketSummary(combined_df)
	println(summary)

	spread = PermutationSpreadByBucket(summary)
	println(spread)

	p_fixed = PlotPriceBucketComparison("Fixed", summary[summary.Case .== "Fixed", :])
	savefig(p_fixed, "$results_path_base/trading_volume_price_bucket_fixed36h.png")
	println("saved: $results_path_base/trading_volume_price_bucket_fixed36h.png")

	p_rolling = PlotPriceBucketComparison("Rolling", summary[summary.Case .== "Rolling", :])
	savefig(p_rolling, "$results_path_base/trading_volume_price_bucket_rolling36h.png")
	println("saved: $results_path_base/trading_volume_price_bucket_rolling36h.png")

	XLSX.writetable("$results_path_base/price_bucket_trading_volume_details.xlsx",
		"by_generator" => combined_df,
		"summary" => summary,
		"permutation_spread" => spread;
		overwrite=true,
	)
	println("saved: $results_path_base/price_bucket_trading_volume_details.xlsx")

	return (p_fixed, p_rolling, combined_df, summary, spread)
end

end;
