
# Generator parameters
dispatchableGenerators:
 Base:
  bidPrice: 30 # EUR/MWh
  capacity: 6000 # MW
  rampRate: 0.3333333333333333 # % of nominal power per minute
  initialQuantity: 4800
  emissionFactor: 980 # kgCO2e/MWh

 Shoulder:
  bidPrice: 80 # EUR/MWh
  capacity: 4000 # MW
  rampRate: 0.8333333333333333 # % of nominal power per minute
  initialQuantity: 2000
  emissionFactor: 420 # kgCO2e/MWh

 Peak:
  bidPrice: 150 # EUR/MWh
  capacity: 5000 # MW
  rampRate: 1.666666666666666667 # % of nominal power per minute
  initialQuantity: 0
  emissionFactor: 420 # kgCO2e/MWh

variableGenerators:
  Wind:
    bidPrice: 0         # EUR/MWh
    capacity: 12000        # MW
    profile_files: ["../DATA/inputs/laura/windon_data_2025_ned.csv", "../DATA/inputs/laura/windoff_data_2025_ned.csv"] # note, laura combines wind on and off by addition
    profile_type: quantity
    conversionFactor: 0.00095  # Convert kW to MW and scale renewables to 95%
  Solar:
    bidPrice: 0         # EUR/MWh
    capacity: 29000        # MW
    profile_file: ../DATA/inputs/laura/solar_data_2025_ned.csv
    profile_type: quantity 
    conversionFactor: 0.00095  # Convert kW to MW and scale renewables to 95%

# Storage parameters
batteryStorage:
  energyCapacity: 6000 # MWh
  powerCapacity: 2000 # MW
  efficiency: 0.9
  initialSOC: 0.0 # as fraction of energyCapacity
  endSOC: 0.0 # as fraction of energyCapacity
  
# Demand parameters
demand:
  segments:
    Base_D:
      bidPrice: 300   # EUR/MWh (high willingness to pay)
      profile_file: ../DATA/inputs/laura/demand_data_2025_ned2.csv
      profile_type: quantity
      conversionFactor: 0.0009  # Convert kW to MW, 90% 0.001*.9 = .0009
    Flex:
      bidPrice: 50   # EUR/MWh (elastic, only if price low)
      profile_file: ../DATA/inputs/laura/demand_data_2025_ned2.csv
      profile_type: quantity
      conversionFactor: 0.0001  # Convert kW to MW, 10%