# This configuration resembles the status quo markets in Europe, etc (simplified to 1 intraday)
# Define a set of markets that will be cleared over the course of the experiment
# all parameters are expressed in MTU - in this case 15m

timePeriodsPerDay: 96 # define the assumed MTU for this market configuration - this allows for validation that this market is appropriate for the experiment

marketSequence:
  DayAhead: # name of market
    clearingInterval: 96 # number of MTU between market clearing/optimization rounds
    optimizationWindow: 96 # number of MTU to consider in each clearing
    lookAheadDistance: 48 # number of MTU after which to start optimization window
    clockTimeBegin: 48 # number of MTU after midnight to hold first clearing
  Intraday1: # name of market
    clearingInterval: 96 # number of MTU between market clearing/optimization rounds
    optimizationWindow: 96 # number of MTU to consider in each clearing
    lookAheadDistance: 8 # number of MTU after which to start optimization window
    clockTimeBegin: 88 # number of MTU after midnight to hold first clearing
